Repository shardlab/discordrb, pull requests merged in 2022-10, with the labels that each got.

#179 Prepare for discord deprecations
  lib/discordrb/gateway.rb
Labels: hacktoberfest-accepted

#151 Add new channel types.
  lib/discordrb/data/channel.rb
Labels: enhancement, hacktoberfest-accepted

#150 feat: add modals
  examples/modals.rb
  lib/discordrb/api/interaction.rb
  lib/discordrb/bot.rb
  lib/discordrb/container.rb
  lib/discordrb/data/component.rb
  lib/discordrb/data/interaction.rb
  lib/discordrb/events/interactions.rb
  lib/discordrb/webhooks.rb
  lib/discordrb/webhooks/modal.rb
Labels: enhancement, hacktoberfest-accepted

#172 feat: add user badges
  lib/discordrb/data/user.rb
  spec/api/channel_spec.rb
Labels: enhancement, hacktoberfest-accepted

#99 Minor fixes and making style consistent in Markdown files
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .markdownlint.json
  CHANGELOG.md
  README.md
Labels: documentation, hacktoberfest-accepted

#181 #application_command_response and #type for message
  lib/discordrb/data/message.rb
Labels: enhancement, hacktoberfest-accepted
