Repository shardlab/discordrb, pull requests merged in 2022-04, with the labels that each got.

#95 Store RSpec metadata on CircleCI
  .circleci/config.yml
  discordrb.gemspec
Labels: ci, hacktoberfest-accepted

#54 Fix YARD for Message#reply
  lib/discordrb/data/message.rb
Labels: documentation, need input

#86 Deprecate group DM endpoint methods
  lib/discordrb/api/channel.rb
Labels: documentation
